import {PropsWithChildren} from 'react'
import styles from './MainLayout.module.css'
import Head from 'next/head'
import Navbar from '../Navbar'

const MainLayout = ({ children } : PropsWithChildren<unknown>) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />

            <main className={styles.main}>
                {children}
            </main>


        </div>
    )
}

export default MainLayout